title: Yi Yu
logo: /assets/img/logo.jpg
description: "Postdoctoral Scholar, Ohio State University. Email: yu.4432@osu.edu"
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
