title: Yi Yu
logo: /assets/img/logo.jpg
description: "Postdoc (research associate)\nSoutheast University\nEmail: yuyi@seu.edu.cn"
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
